#连接池
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Zhangxiang0518
    url: jdbc:mysql://localhost:3306/bill-manager?serverTimezone=UTC&&useSSL=false
  thymeleaf:
    cache: false #关闭thymeleaf缓存
  application:
    name: bill-service
#mybatis
mybatis:
  type-aliases-package: com.kkb.entity #别名搜索
  mapper-locations: classpath:/mybatis/*.xml
server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
